apiVersion: apps/v1
kind: Deployment
metadata:
  name: supervisor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supervisor
  template:
    metadata:
      labels:
        app: supervisor
    spec:
      containers:
        - name: supervisor
          image: supervisor:latest
          imagePullPolicy: Never
          env:
            - name: OPAMP_SERVER_URL
              value: "ws://opamp-server.opamp-system.svc.cluster.local:4320/v1/opamp"
          ports:
            - containerPort: 50051
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: supervisor
spec:
  selector:
    app: supervisor
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
